### PR TITLE
Adding Linter

### LINKED ISSUE #356: Linter Automation
https://github.com/blocklistproject/Lists/commit/71ecb46b74c394b01593df71a117abd9eaaf2d8e

As part of the linter automation, we should ensure a valid style here. All domains should start with `0.0.0.0` followed by a space. In the commit above there was a tab instead of a space after the `0.0.0.0` part. In that event an error or warning should be thrown so that it can be corrected.

### PR DESCRIPTION
**Pull request by fishcharlie**
## Summary

This PR adds a linter to ensure that the format of the lists is correct.

Close #356 

## Checklist

- [x] I have verified that I have not modified any files inside the `alt-version` folder (automated code will automatically update those files)

- [x] I have verified that I have not modified any files inside the `dnsmasq-version` folder (automated code will automatically update those files)

### CODE REVIEW

**Comment by fishcharlie** [comment]
cb5e125 should fail due to a lot of URLs being uppercase. After validating that is does indeed fail on GitHub Actions I will fix the errors then merge.

**Comment by blocklistproject** [comment]
Can you resolved conflicting files please.

**Comment by fishcharlie** [comment]
@blocklistproject Yes! I can do that when I get a chance.

**Comment by fishcharlie** [comment]
@blocklistproject The merge conflicts have been resolved.

**Review by blocklistproject — APPROVED** [review]

**Pull request merged**
