### PR TITLE
🚸 make PR Template clearer to contributor what to change - and what not

### PR DESCRIPTION
**Pull request by thomasmerz**
## Summary

This PR makes clearer what contributors should NOT edit:

- [x] I have verified that I have not modified the following files:
      - inside the `alt-version` folder
      - inside the `dnsmasq-version` folder
      - everything.txt

Because automated code will automatically update those files!

## Checklist

- [x] I have verified that I have not modified any files inside the `alt-version` folder (automated code will automatically update those files)

- [x] I have verified that I have not modified any files inside the `dnsmasq-version` folder (automated code will automatically update those files)

### CODE REVIEW

**Comment by fishcharlie** [comment]
@thomasmerz This actually looks to apply to all of your open PRs. Maybe a Git error was made when trying to modify things?? Not sure. I don't want to close all your open PRs, but this needs to be corrected before merging.

**Comment by thomasmerz** [comment]
@fishcharlie I will investigate and try to fix it.

**Comment by thomasmerz** [comment]
Here we go with a new PR #673 @fishcharlie

**Comment by thomasmerz** [comment]
The problem came up when I "fetch upstream" into my fork, so your GH action was updating some files in my master branch 😲 Then I made some rebases into my other branches/PRs and that's the way it has gone… 🤷🏻‍♂️

**Pull request closed without merging**
