### PR TITLE
fix for issues/572: punycoded domain instead of IDN domain

### PR DESCRIPTION
**Pull request by thomasmerz**
## Summary

This fixes https://github.com/blocklistproject/Lists/issues/572

## Checklist

- [x] I have verified that I have not modified any files inside the `alt-version` folder (automated code will automatically update those files)

- [x] I have verified that I have not modified any files inside the `dnsmasq-version` folder (automated code will automatically update those files)

### CODE REVIEW

**Comment by thomasmerz** [comment]
Rebase done as described in PR https://github.com/blocklistproject/Lists/pull/574 👍🏻

**Comment by thomasmerz** [comment]
@cryptogap , please review and merge when appropriate. Thank you!

**Comment by fishcharlie** [comment]
Can't view the diff on this on GitHub. @thomasmerz if you could investigate this please that'd be awesome.

**Comment by thomasmerz** [comment]
@fishcharlie , this is very strange… 🤔 I can view the diff on this on GitHub:

grafik

**Comment by spirillen** [comment]
> Can't view the diff on this on GitHub. @thomasmerz if you could investigate this please that'd be awesome.


```
git diff 11111111..22222222 relative/path/file 

Whereas:
   - 11111111 is parent
   - 22222222 is current commit
```

This said, I get same issue while trying to view the diff in the browser

image

**Comment by thomasmerz** [comment]
@spirillen , I understand 😁 
```
🦎🖥  ✔ ~/temp/PRs/blocklistproject-Lists [issues/572|✔]
21:52 $ git show
commit 565be741202affd44bc5a79f064f5a3879480f54 (HEAD -> issues/572, origin/issues/572)
Author: Thomas Merz <git@rhoenwurz.de>
Date:   Wed Nov 24 14:06:09 2021 +0100

    fix for issues/572: punycoded domain instead of IDN domain

diff --git a/adguard/everything-ags.txt b/adguard/everything-ags.txt
index adfb2bf..7dd73c3 100644
--- a/adguard/everything-ags.txt
+++ b/adguard/everything-ags.txt
@@ -3044279,7 +3044279,7 @@
 ||www.putalocura.com^
 ||www.naoconto.com^
 ||www.poringa.net^
-||www.xvideos-español.com^
+||www.xn--xvideos-espaol-1nb.com^
 ||www.lechetube.com^
 ||www.gulfsexx.com^
 ||sex4arabxxx.com^
diff --git a/adguard/porn-ags.txt b/adguard/porn-ags.txt
index b901238..b36d857 100644
--- a/adguard/porn-ags.txt
+++ b/adguard/porn-ags.txt
@@ -1907951,7 +1907951,7 @@
 ||www.putalocura.com^
 ||www.naoconto.com^
 ||www.poringa.net^
-||www.xvideos-español.com^
+||www.xn--xvideos-espaol-1nb.com^
 ||www.lechetube.com^
 ||www.gulfsexx.com^
 ||sex4arabxxx.com^
diff --git a/everything.txt b/everything.txt
index d02f4ee..550e155 100644
--- a/everything.txt
+++ b/everything.txt
@@ -3044279,7 +3044279,7 @@
 0.0.0.0 www.putalocura.com
 0.0.0.0 www.naoconto.com
 0.0.0.0 www.poringa.net
-0.0.0.0 www.xvideos-español.com
+0.0.0.0 www.xn--xvideos-espaol-1nb.com
 0.0.0.0 www.lechetube.com
 0.0.0.0 www.gulfsexx.com
 0.0.0.0 sex4arabxxx.com
diff --git a/porn.txt b/porn.txt
index da222cc..d99d159 100644
--- a/porn.txt
+++ b/porn.txt
@@ -1907951,7 +1907951,7 @@
 0.0.0.0 www.putalocura.com
 0.0.0.0 www.naoconto.com
 0.0.0.0 www.poringa.net
-0.0.0.0 www.xvideos-español.com
+0.0.0.0 www.xn--xvideos-espaol-1nb.com
 0.0.0.0 www.lechetube.com
 0.0.0.0 www.gulfsexx.com
 0.0.0.0 sex4arabxxx.com
🦎🖥  ✔ ~/temp/PRs/blocklistproject-Lists [issues/572|✔]
21:53 $
```

**Comment by thomasmerz** [comment]
And a `git diff` after rebasing against current master:
```
🦎🖥  ✔ ~/temp/PRs/blocklistproject-Lists [issues/572|✔]
21:59 $ git diff 74ebff199da62bef34a00911851af25531203447
diff --git a/adguard/everything-ags.txt b/adguard/everything-ags.txt
index 3ae4b4b..e562dc0 100644
--- a/adguard/everything-ags.txt
+++ b/adguard/everything-ags.txt
@@ -3044289,7 +3044289,7 @@
 ||www.putalocura.com^
 ||www.naoconto.com^
 ||www.poringa.net^
-||www.xvideos-español.com^
+||www.xn--xvideos-espaol-1nb.com^
 ||www.lechetube.com^
 ||www.gulfsexx.com^
 ||sex4arabxxx.com^
diff --git a/adguard/porn-ags.txt b/adguard/porn-ags.txt
index b901238..b36d857 100644
--- a/adguard/porn-ags.txt
+++ b/adguard/porn-ags.txt
@@ -1907951,7 +1907951,7 @@
 ||www.putalocura.com^
 ||www.naoconto.com^
 ||www.poringa.net^
-||www.xvideos-español.com^
+||www.xn--xvideos-espaol-1nb.com^
 ||www.lechetube.com^
 ||www.gulfsexx.com^
 ||sex4arabxxx.com^
diff --git a/everything.txt b/everything.txt
index 9044a52..6ffdb52 100644
--- a/everything.txt
+++ b/everything.txt
@@ -3044289,7 +3044289,7 @@
 0.0.0.0 www.putalocura.com
 0.0.0.0 www.naoconto.com
 0.0.0.0 www.poringa.net
-0.0.0.0 www.xvideos-español.com
+0.0.0.0 www.xn--xvideos-espaol-1nb.com
 0.0.0.0 www.lechetube.com
 0.0.0.0 www.gulfsexx.com
 0.0.0.0 sex4arabxxx.com
diff --git a/porn.txt b/porn.txt
index da222cc..d99d159 100644
--- a/porn.txt
+++ b/porn.txt
@@ -1907951,7 +1907951,7 @@
 0.0.0.0 www.putalocura.com
 0.0.0.0 www.naoconto.com
 0.0.0.0 www.poringa.net
-0.0.0.0 www.xvideos-español.com
+0.0.0.0 www.xn--xvideos-espaol-1nb.com
 0.0.0.0 www.lechetube.com
 0.0.0.0 www.gulfsexx.com
 0.0.0.0 sex4arabxxx.com
🦎🖥  ✔ ~/temp/PRs/blocklistproject-Lists [issues/572|✔]
21:59 $
```

**Comment by spirillen** [comment]
The git diff was to @fishcharlie

**Pull request merged**
