### PR TITLE
🚸 Remove ipfs.io as a false positive from all blocklists

### PR DESCRIPTION
**Pull request by thomasmerz**
## Summary
This PR will remove ipfs.io from any blocklist:
-    adguard/crypto-ags.txt
-    adguard/everything-ags.txt
-    crypto.txt
-    everything.txt

More details about ipfs can be found here:
-    https://docs.ipfs.io/concepts/what-is-ipfs/
-    https://en.wikipedia.org/wiki/InterPlanetary_File_System

## Checklist

- [x] I have verified that I have not modified any files inside the `alt-version` folder (automated code will automatically update those files)

- [x] I have verified that I have not modified any files inside the `dnsmasq-version` folder (automated code will automatically update those files)

`sed -i '/ipfs.io/d' $(ack ipfs.io -l|grep -vE "alt-version|dnsmasq-version")`
```
$ git whatchanged
…
:100644 100644 993b8ef 1474c41 M        adguard/crypto-ags.txt
:100644 100644 4e2eaab 0963c6e M        adguard/everything-ags.txt
:100644 100644 91a08b6 05cda57 M        crypto.txt
:100644 100644 190354b a0aaf5c M        everything.txt
```

### CODE REVIEW

**Comment by thomasmerz** [comment]
@cryptogap or @fishcharlie , **you should check the linting**, because I didn't change anything regarding this:
```
Run node scripts/lint.js
Line 67777 in ads.txt should have a space after #.
Line 67777 in ads.txt should start with "# 0.0.0.0" or "# NOTE:".
…
Line 42832 in phishing.txt should have a space after #.
Line 42832 in phishing.txt should start with "# 0.0.0.0" or "# NOTE:".
…
Line 38046 in malware.txt should have a space after #.
Line 38046 in malware.txt should start with "# 0.0.0.0" or "# NOTE:".
…
Line 20529 in abuse.txt should have a space after #.
Line 20529 in abuse.txt should start with "# 0.0.0.0" or "# NOTE:".
…
Line 962973 in porn.txt should have a space after #.
Line 962973 in porn.txt should start with "# 0.0.0.0" or "# NOTE:".
Error: Process completed with exit code 1.
```
😕

**Comment by fishcharlie** [comment]
@thomasmerz It looks to be caused by 1a8ddee7dfa01743c3c8c6c63b70c37818ca9d3a.

Really up to @cryptogap to implement and stick to policies to avoid this in the future.

Requiring all commits to be made through pull requests and ensure that all checks pass before merging would solve this problem.

However unless policy is implemented, things like this will likely continue to occur.

Not much I can do here.

**Comment by thomasmerz** [comment]
You might already know this, but just for "information":
* protect HEAD branch
* set some repo-settings to benefit of the GH actions:

   grafik

**Comment by thomasmerz** [comment]
@fishcharlie, I fixed it and checked it **before** pushing with a little help from [act](https://github.com/nektos/act) by running this GH workflow locally:
```
…
[Lint/lint  ] ⭐  Run node scripts/lint.js
[Lint/lint  ]   🐳  docker exec cmd=[bash --noprofile --norc -e -o pipefail /home/thomas/temp/PRs/Lists/workflow/2] user= workdir=
[Lint/lint  ]   ✅  Success - node scripts/lint.js
…
```
😃

**Comment by thomasmerz** [comment]
Hm, I thought I could resolve some conflicts that came because I didn't use a separate branch in my fork, and your HEAD got some new commits that led to some conflicts. But GH closed this PR with my remediations (or I did make something "wrong?) 🤷🏻‍♂️
So there's now a new PR for this: #643

**Pull request closed without merging**
