### PR TITLE
fix for issues/571: punycoded domains instead of IDN domains

### LINKED ISSUE #571: [Remove Request] - invalid domains due to IDN instead of punycode
URL you wish to be removed:
There are some (7) IDN domains in the blocklist that should be or already are converted to punycode:
     - госулуги.рф
      - госуслуги-ру.рф
      - гослуги.рф
      - госсуслуга.рф
      - госсуслуугии.рф

Why you believe this to be a false positive:
Output from Pi-Hole preparing new gravity database:
```
  [i] Target: https://raw.githubusercontent.com/blocklistproject/Lists/master/phishing.txt
  [✓] Status: Retrieval successful
  [i] Analyzed 190258 domains, 7 domains invalid!
      Sample of invalid domains:
      - госулуги.рф
      - госуслуги-ру.рф
      - гослуги.рф
      - госсуслуга.рф
      - госсуслуугии.рф
  [i] List has been updated
```

List it is on:
phishing

### PR DESCRIPTION
**Pull request by thomasmerz**
## Summary

This fixes #571

## Checklist

- [x] I have verified that I have not modified any files inside the `alt-version` folder (automated code will automatically update those files)

- [x] I have verified that I have not modified any files inside the `dnsmasq-version` folder (automated code will automatically update those files)

### CODE REVIEW

**Comment by cryptogap** [comment]
Failing checks, please review

**Comment by thomasmerz** [comment]
That's very "interesting", because I didn't change anything in `twitter.txt` 😕 🤷🏻‍♂️ 
```
Wed, 22 Dec 2021 12:31:55 GMT
Run node scripts/lint.js
Wed, 22 Dec 2021 12:31:55 GMT Line 28 in twitter.txt should start with "# 0.0.0.0".
Wed, 22 Dec 2021 12:31:55 GMT Line 50 in twitter.txt should start with "# 0.0.0.0".
Wed, 22 Dec 2021 12:32:07 GMT Error: Process completed with exit code 1.
```
This has already been faulty in [my previous PR](https://github.com/blocklistproject/Lists/issues/570) and [your merge](https://github.com/blocklistproject/Lists/runs/4606805940?check_suite_focus=true).

Both lines [start with "#" or "0.0.0.0 "](https://github.com/blocklistproject/Lists/blob/master/scripts/lint.js#L25) or [start with `#` are followed by a space](https://github.com/blocklistproject/Lists/blob/master/scripts/lint.js#L41), but bot don't [start with `# 0.0.0.0` or `# NOTE:`](https://github.com/blocklistproject/Lists/blob/master/scripts/lint.js#L47). Ok, I found it. But why is it me, that has to fix this? 🤔 

It looks like [your commit on Nov 28th](https://github.com/blocklistproject/Lists/commit/89ed26dd5ab525b1109edff1ffd9c5f7097d8514) has changed the linting checks since I opened this (and my previous PR) on Nov 24th and I didn't rebase yet 😞 

Rebase done 👍🏻

**Comment by thomasmerz** [comment]
@cryptogap , please review and merge when appropriate. Thank you!

**Comment by iam-py-test** [comment]
Thanks @fishcharlie

**Pull request merged**
