### PR TITLE
Removed some other domains, moved some and added some others

### LINKED ISSUE #154: [Remove Request] - dege.freeweb.hu
URL you wish to be removed: dege.freeweb.hu

Why you believe this to be a false positive: This is a software developer's personal site. They host tools for running old games.

List it is on: abuse, malware 

Other info you think we should know:

### LINKED ISSUE #156: [Remove Request] -
URL you wish to be removed:
mc.yandex.ru

Why you believe this to be a false positive:
its tracking. not torrent

List it is on:
torrent

Other info you think we should know:

### LINKED ISSUE #157: [Add request] ruutu.fi/nelonenmedia related urls
URLs you wish to be added:  
- nelonenmedia-pmd-ads-promo.nm-stream.nelonenmedia.fi
- nelonenmedia-pmd-ads-spotgate.nm-stream.nelonenmedia.fi
- nelonenmedia-pmd-ads-manual.nm-stream.nelonenmedia.fi

Why you believe this should be added: These are ruutu.fi services AD urls.

Add to list: Ads

Other info you think we should know: This is related to playing content from ruutu.fi.

### LINKED ISSUE #158: [Remove Request] - www.interia.pl
URL you wish to be removed:
www.interia.pl

Why you believe this to be a false positive:
It's the whole information service website

List it is on:
Ads

Other info you think we should know:
There are some ads etc. websites under interia.pl which should stay in their respective lists.

### LINKED ISSUE #159: [Add request] analytics.prod.mybuddy.ai
URL you wish to be added: analytics.prod.mybuddy.ai

Why you believe this should be added: tracking domain from buddy.ai android app

Add to list: tracking

### LINKED ISSUE #161: [Remove Request] - surfshark.com
URL you wish to be removed: surfshark.com

Why you believe this to be a false positive: I can't access this website, but I can still connect to VPN.

List it is on: https://blocklistproject.github.io/Lists/torrent.txt

Other info you think we should know: This is not torrent. It's VPN.

### PR DESCRIPTION
**Pull request by Trainax**
This PR closes #154, closes #156, closes #157, closes #158, closes #159, closes #161

I wasn't able to remove the domains from the "everything" lists as those lists were to big and I couldn't commit the changes, so you have to remove those domain from those lists yourself

### CODE REVIEW

**Comment by Trainax** [comment]
I also removed ip-api.com from the lists as I needed it for a university project and is a very useful tool to get info about domains and IPs. I think it's a false positive as I didn't notice any strange behaviour while using it

**Comment by Trainax** [comment]
Removed mc.yandex.ru from torrent and crypto lists -> Closes #156 

Added nelonenmedia-pmd-ads-promo.nm-stream.nelonenmedia.fi, nelonenmedia-pmd-ads-spotgate.nm-stream.nelonenmedia.fi, nelonenmedia-pmd-ads-manual.nm-stream.nelonenmedia.fi -> Closes #157

**Comment by blocklistproject** [comment]
Thank you so much!

**Comment by Trainax** [comment]
> Thank you so much!

You're welcome! 🙂

If I can help somehow I'm happy to help since I really like this project 👍🏻

**Pull request merged**
