### PR TITLE
fix for issues/620: docmorris.de is not an online-shop for drugs

### PR DESCRIPTION
**Pull request by thomasmerz**
… , but for medicine in germany

## Summary
This PR removes some false positive domains for a german online-shop for medicine from drugs-list by
```
s=docmorris.de
sed -i "/$s/d" $(ack $s -l|grep -vE "alt-version|dnsmasq-version")
```

## Checklist

- [x] I have verified that I have not modified any files inside the `alt-version` folder (automated code will automatically update those files)

- [x] I have verified that I have not modified any files inside the `dnsmasq-version` folder (automated code will automatically update those files)

### CODE REVIEW

**Comment by thomasmerz** [comment]
`git diff`
```
🦎🖥  ✔ ~/temp/PRs/blocklistproject-Lists [issues/620|✔]
22:20 $ git diff master
diff --git a/adguard/drugs-ags.txt b/adguard/drugs-ags.txt
index f242648..4c2dd59 100644
--- a/adguard/drugs-ags.txt
+++ b/adguard/drugs-ags.txt
@@ -4903,7 +4903,6 @@
 ||docitmed.sg^
 ||doclamp.com^
 ||docmedbill.sg^
-||docmorris.de^
 ||docrxgp.com^
 ||doctorabout.com^
 ||doctoralq.ru^
@@ -20187,7 +20186,6 @@
 ||www.dmhnch.xn--c1akiqp2bma.xn--p1ai^
 ||www.dmviagratruykfj.com^
 ||www.dnviagrarudfh.com^
-||www.docmorris.de^
 ||www.docrxgp.com^
 ||www.doctormyrx.com^
 ||www.doctorsolve.com^
diff --git a/adguard/everything-ags.txt b/adguard/everything-ags.txt
index 3ae4b4b..c11e619 100644
--- a/adguard/everything-ags.txt
+++ b/adguard/everything-ags.txt
@@ -56403,7 +56403,6 @@
 ||docitmed.sg^
 ||doclamp.com^
 ||docmedbill.sg^
-||docmorris.de^
 ||docrxgp.com^
 ||doctorabout.com^
 ||doctoralq.ru^
@@ -71686,7 +71685,6 @@
 ||www.dmhnch.xn--c1akiqp2bma.xn--p1ai^
 ||www.dmviagratruykfj.com^
 ||www.dnviagrarudfh.com^
-||www.docmorris.de^
 ||www.docrxgp.com^
 ||www.doctormyrx.com^
 ||www.doctorsolve.com^
diff --git a/drugs.txt b/drugs.txt
index 6cadca2..877dcfc 100644
--- a/drugs.txt
+++ b/drugs.txt
@@ -4903,7 +4903,6 @@
 0.0.0.0 docitmed.sg
 0.0.0.0 doclamp.com
 0.0.0.0 docmedbill.sg
-0.0.0.0 docmorris.de
 0.0.0.0 docrxgp.com
 0.0.0.0 doctorabout.com
 0.0.0.0 doctoralq.ru
@@ -20187,7 +20186,6 @@
 0.0.0.0 www.dmhnch.xn--c1akiqp2bma.xn--p1ai
 0.0.0.0 www.dmviagratruykfj.com
 0.0.0.0 www.dnviagrarudfh.com
-0.0.0.0 www.docmorris.de
 0.0.0.0 www.docrxgp.com
 0.0.0.0 www.doctormyrx.com
 0.0.0.0 www.doctorsolve.com
diff --git a/everything.txt b/everything.txt
index 9044a52..650ace0 100644
--- a/everything.txt
+++ b/everything.txt
@@ -56403,7 +56403,6 @@
 0.0.0.0 docitmed.sg
 0.0.0.0 doclamp.com
 0.0.0.0 docmedbill.sg
-0.0.0.0 docmorris.de
 0.0.0.0 docrxgp.com
 0.0.0.0 doctorabout.com
 0.0.0.0 doctoralq.ru
@@ -71686,7 +71685,6 @@
 0.0.0.0 www.dmhnch.xn--c1akiqp2bma.xn--p1ai
 0.0.0.0 www.dmviagratruykfj.com
 0.0.0.0 www.dnviagrarudfh.com
-0.0.0.0 www.docmorris.de
 0.0.0.0 www.docrxgp.com
 0.0.0.0 www.doctormyrx.com
 0.0.0.0 www.doctorsolve.com
🦎🖥  ✔ ~/temp/PRs/blocklistproject-Lists [issues/620|✔]
```
grafik

**Comment by thomasmerz** [comment]
`git show`
```
commit 399004c450dd215443701dd040ae902b0b5dfb4c (HEAD -> issues/620, origin/issues/620)
Author: Thomas Merz <git@rhoenwurz.de>
Date:   Wed Jan 19 22:12:27 2022 +0100

    fix for issues/620: docmorris.de is not an online-shop for drugs, but for medicine in germany

diff --git a/adguard/drugs-ags.txt b/adguard/drugs-ags.txt
index f242648..4c2dd59 100644
--- a/adguard/drugs-ags.txt
+++ b/adguard/drugs-ags.txt
@@ -4903,7 +4903,6 @@
 ||docitmed.sg^
 ||doclamp.com^
 ||docmedbill.sg^
-||docmorris.de^
 ||docrxgp.com^
 ||doctorabout.com^
 ||doctoralq.ru^
@@ -20187,7 +20186,6 @@
 ||www.dmhnch.xn--c1akiqp2bma.xn--p1ai^
 ||www.dmviagratruykfj.com^
 ||www.dnviagrarudfh.com^
-||www.docmorris.de^
 ||www.docrxgp.com^
 ||www.doctormyrx.com^
 ||www.doctorsolve.com^
diff --git a/adguard/everything-ags.txt b/adguard/everything-ags.txt
index 3ae4b4b..c11e619 100644
--- a/adguard/everything-ags.txt
+++ b/adguard/everything-ags.txt
@@ -56403,7 +56403,6 @@
 ||docitmed.sg^
 ||doclamp.com^
 ||docmedbill.sg^
-||docmorris.de^
 ||docrxgp.com^
 ||doctorabout.com^
 ||doctoralq.ru^
@@ -71686,7 +71685,6 @@
 ||www.dmhnch.xn--c1akiqp2bma.xn--p1ai^
 ||www.dmviagratruykfj.com^
 ||www.dnviagrarudfh.com^
-||www.docmorris.de^
 ||www.docrxgp.com^
 ||www.doctormyrx.com^
 ||www.doctorsolve.com^
diff --git a/drugs.txt b/drugs.txt
index 6cadca2..877dcfc 100644
--- a/drugs.txt
+++ b/drugs.txt
@@ -4903,7 +4903,6 @@
 0.0.0.0 docitmed.sg
 0.0.0.0 doclamp.com
 0.0.0.0 docmedbill.sg
-0.0.0.0 docmorris.de
 0.0.0.0 docrxgp.com
 0.0.0.0 doctorabout.com
 0.0.0.0 doctoralq.ru
@@ -20187,7 +20186,6 @@
 0.0.0.0 www.dmhnch.xn--c1akiqp2bma.xn--p1ai
 0.0.0.0 www.dmviagratruykfj.com
 0.0.0.0 www.dnviagrarudfh.com
-0.0.0.0 www.docmorris.de
 0.0.0.0 www.docrxgp.com
 0.0.0.0 www.doctormyrx.com
 0.0.0.0 www.doctorsolve.com
diff --git a/everything.txt b/everything.txt
index 9044a52..650ace0 100644
--- a/everything.txt
+++ b/everything.txt
@@ -56403,7 +56403,6 @@
 0.0.0.0 docitmed.sg
 0.0.0.0 doclamp.com
 0.0.0.0 docmedbill.sg
-0.0.0.0 docmorris.de
 0.0.0.0 docrxgp.com
 0.0.0.0 doctorabout.com
 0.0.0.0 doctoralq.ru
@@ -71686,7 +71685,6 @@
 0.0.0.0 www.dmhnch.xn--c1akiqp2bma.xn--p1ai
 0.0.0.0 www.dmviagratruykfj.com
 0.0.0.0 www.dnviagrarudfh.com
-0.0.0.0 www.docmorris.de
 0.0.0.0 www.docrxgp.com
 0.0.0.0 www.doctormyrx.com
 0.0.0.0 www.doctorsolve.com
```
grafik

**Review by fishcharlie — CHANGES_REQUESTED** [review]
We should change the PR template. But the only file that should be edited here is `drugs.txt`. All the others are generated automatically.

**Comment by thomasmerz** [comment]
Hi @fishcharlie , I reverted all other files except `drugs.txt`.

**Pull request merged**
