### PR TITLE
AdobeBlock.txt

### PR DESCRIPTION
**Pull request by PJGitHub9**
adobeblock

## Summary

Added in Adobe list

## Checklist

- [x] I have verified that I have not modified the following files:
      - inside the `adguard` folder
      - inside the `alt-version` folder
      - inside the `dnsmasq-version` folder
      - everything.txt

Because those files will be automatically updated using GitHub Actions!

### CODE REVIEW

**Comment by thomasmerz** [comment]
@PJGitHub9 , what's this? A complete new blocklist for Adobe service? Maybe you should update also `README.md` to give a description about this new list 🤔   

What do you think @cryptogap ?

**Comment by thomasmerz** [comment]
This solves issue #862

**Comment by blocklistproject** [comment]
Before we can pull this in it will have to formatted correctly. I will see if I can get it formatted soon

**Comment by PJGitHub9** [comment]
> @PJGitHub9 , what's this? A complete new blocklist for Adobe service? Maybe you should update also `README.md` to give a description about this new list 🤔
> 
> What do you think @cryptogap ?

Yessir! I rarely use github so i'm not too sure how pulling/editting works. Getting a txt file up took me a while haha. 

The list is everything from Adobe's website + from various sources (blocking ip's for tracking etc)

**Comment by blocklistproject** [comment]
> 

It took me a while to grasp GH too!

**Comment by blocklistproject** [comment]
Created this list but it is highly experimental

**Pull request closed without merging**
