### PR TITLE
Remove shrtm.nu from phishing.txt

### PR DESCRIPTION
**Pull request by floschliep**
## Summary

This removes `shrtm.nu` from phishing.txt. It's the domain for a URL shortener that I own/maintain.
I assume the domain was wrongfully added here due to some criminal abusing the service for a phishing attack.
As the service is used by the vast majority of people for legitimate purposes and illegal activity is monitored and taken action on, I don't think the domain should be listed here.

## Checklist

- [x] I have verified that I have not modified the following files:
      - inside the `adguard` folder
      - inside the `alt-version` folder
      - inside the `dnsmasq-version` folder
      - everything.txt

### CODE REVIEW

**Comment by spirillen** [comment]
Well, you are well represented on various lists, even those that haven't been maintained for a very long time....

## Search result from External Hosts-Sources
@mypdns's External Hosts-Sources can be found [here](https://github.com/external-sources/hosts-sources?tab=readme-ov-file#external-sources)

```css
data/UltimateHostsBlacklist2.txt:shrtm.nu
data/hphosts/psh/domain.list:shrtm.nu
data/hphosts/psh/domain.list:www.shrtm.nu
```

#### Sorted result

```css
www.shrtm.nu
```

### Search result from easylist

```css
```

## Search in [Matrix](https://mypdns.org/)


Search results from [Matrix](https://mypdns.org) blacklist project

```css
```


Did not find any matching RPZ records


+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
\+ Thanks to [My Privacy DNS](https://mypdns.org/) for this knowledge
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by floschliep** [comment]
@spirillen Thanks for the helpful pointer – I'll take a look at these.

I only recently became aware of the listings through a customer report who was using NextDNS, which in return uses some of these lists internally. Now I'm trying to make my way through and see what's the damage.

Would I need to remove the domain from the other lists so that we can remove it from this repo?

**Comment by spirillen** [comment]
I'm afraid your changes to get off this list seems slim... https://github.com/blocklistproject/Lists/issues/1210 As it looks like this project have been abandon by it's maintainers as last commit was 6 month ago `Jan 8 2024`

But for the other, you'll need to find the upstream sources and request removal from those lists

I have opened the issue regarding this domain in my domain index project and we can continue the talk over there, as I have no other powers here than trying to spread knowledge and being helpful

**Comment by floschliep** [comment]
@spirillen Amazing, thanks for your community support here – hadn't realized this project was abandoned.

**Pull request merged**
