### PR TITLE
Update gambling.txt

### PR DESCRIPTION
**Pull request by JnBenites**
## Checklist

- [ ] I have verified that I have not modified the following files:
      - inside the `adguard` folder
      - inside the `alt-version` folder
      - inside the `dnsmasq-version` folder
      - everything.txt

Because those files will be automatically updated using GitHub Actions!

### CODE REVIEW

**Comment by JnBenites** [comment]
Add ecuabet.com to a list

**Comment by spirillen** [comment]
Unable to access the domain, can you generate a screenshot of a active domain?

**Comment by JnBenites** [comment]
image

**Comment by spirillen** [comment]
Thanks, added to My Privacy DNS in https://github.com/mypdns/matrix/commit/4ea7fa1e74042027c59c4ac8cab0a836714993f3

**Pull request merged**
