### PR TITLE
🚸 Issue 664: bulk-import of many (750+) porn-domains from @TruthfullEdward

### LINKED ISSUE #664: 518 + 260 additional URL's for p*rn-blocklist
URL you wish to be added:  see documents below

Why you believe this should be added: To make internet for the Pi-Hole user a lot safer

Add to list: all the URL's below

Other info you think we should know:
One .txt file contains URL's with WWW (518) and the second one has URL's from the same list without www (260). All URL's have been tested in Linux for reachability. All of them are still reachable (all URL's from both documents). Please add them all to your blocklist!
[alpha sort FAIL_check (www).txt](https://github.com/blocklistproject/Lists/files/8121311/alpha.sort.FAIL_check.www.txt)
[alpha sort FAIL_check (point).txt](https://github.com/blocklistproject/Lists/files/8121313/alpha.sort.FAIL_check.point.txt)

### PR DESCRIPTION
**Pull request by thomasmerz**
## Summary

This PR fixes #664 by bulk-importing many new (750+) porn-domains from @TruthfullEdward
I checked if there are any duplicates by:
```
🦎🖥  ✔ ~/temp/PRs/Lists [issue_664|✔]
10:14 $ wc -l porn.txt
1908849 porn.txt
🦎🖥  ✔ ~/temp/PRs/Lists [issue_664|✔]
10:14 $ sort -u porn.txt | wc -l
1908849
🦎🖥  ✔ ~/temp/PRs/Lists [issue_664|✔]
10:14 $
```

## Checklist

- [x] I have verified that I have not modified any files inside the `alt-version` folder (automated code will automatically update those files)

- [x] I have verified that I have not modified any files inside the `dnsmasq-version` folder (automated code will automatically update those files)

### CODE REVIEW

**Comment by TruthfullEdward** [comment]
@thomasmerz Thanks a lot! I hope there were not much duplicates left. I sorted the list alphabetically and removed duplicates. If you would have an interesting line of code for my Linux terminal, so I can do that process already for you (the way you like), please let me know!

**Comment by thomasmerz** [comment]
You can remove duplicates beforehand with `sort -u` 👍🏻 

There has been no duplicates:

> I checked if there are any duplicates by:
> ```
> 🦎🖥  ✔ ~/temp/PRs/Lists [issue_664|✔]
> 10:14 $ wc -l porn.txt
> 1908849 porn.txt
> 🦎🖥  ✔ ~/temp/PRs/Lists [issue_664|✔]
> 10:14 $ sort -u porn.txt | wc -l
> 1908849
> 🦎🖥  ✔ ~/temp/PRs/Lists [issue_664|✔]
> 10:14 $
> ```

**Comment by spirillen** [comment]
> @thomasmerz Thanks a lot! I hope there were not much duplicates left. I sorted the list alphabetically and removed duplicates. If you would have an interesting line of code for my Linux terminal, so I can do that process already for you (the way you like), please let me know!


```
sort -u -f file.txt -o file.txt
```

Explain:

sort is a program that... sort lines in a file

-u = uniq, romoves duplicates
-f file to read
-o output to file

the file for -f & -o can be the same, as the file is read to memory for sort and the writes to file.tmp and first then moves the temp file to the destination file

**Comment by TruthfullEdward** [comment]
@spirillen Thanks! I always wrote    sort filename.txt | uniq-u   but that deleted all my file content. I'll give your codeline certainly a try.

**Pull request merged**
