### PR TITLE
Add vaping list

### PR DESCRIPTION
**Pull request by iam-py-test**
## Summary
This PR adds the vaping list, as requested in https://github.com/blocklistproject/Lists/discussions/308
When merged, this will fix https://github.com/blocklistproject/Lists/issues/383

## Checklist

- [X] I have verified that I have not modified any files inside the `alt-version` folder (automated code will automatically update those files)

- [X] I have verified that I have not modified any files inside the `dnsmasq-version` folder (automated code will automatically update those files)

### CODE REVIEW

**Review by fishcharlie — COMMENTED** [review]
Just want to say, so far this looks great!

**Review by fishcharlie — APPROVED** [review]
I think this looks great. Approving this PR on my end.

Gonna wait until @blocklistproject reviews it as well before merging.

**Comment by blocklistproject** [comment]
Are we creating this list to block information about vaping or the sale of vaping products?  

Just wondering what the end result of the list is because we need to be able to articulate this to the community.

**Comment by iam-py-test** [comment]
> Are we creating this list to block information about vaping or the sale of vaping products?
> 
> Just wondering what the end result of the list is because we need to be able to articulate this to the community.

I thought it was just for the promotion of vaping; general information can be helpful

**Comment by blocklistproject** [comment]
I am not opposed to either mission, I just want to make sure I am clear.

**Comment by iam-py-test** [comment]
I have reviewed the domains & removed ones that are not promoting vaping
@doni74 what do you think?

**Pull request merged**
