### PR TITLE
update porn.txt

### PR DESCRIPTION
**Pull request by Avoid0832**
## Summary

Sorting porn.txt.

removing duplicate line:
* goldpornfilms.com

Adding pornographic sites:
* deepmuff.com
* hotnakedgirls.net
* its-porn.net
* itsporn.video
* littlecaprice.cz
* metartmix.com
* pornclap.com
* skinnyhq.com
* teenpornvideo.fun
* www.ametart.com
* www.littlecaprice-dreams.com
* www.metartcom.com
* www.metxhunter.com
* www.picsmetart.com
* www.rednudes.com
* www.xxxftvgirls.com
* x-hd.video

## Checklist

- [x] I have verified that I have not modified the following files:
      - inside the `adguard` folder
      - inside the `alt-version` folder
      - inside the `dnsmasq-version` folder
      - everything.txt

Because those files will be automatically updated using GitHub Actions!

### CODE REVIEW

**Comment by cryptogap** [comment]
Once conflicts are resolved this will be merged in

**Comment by thomasmerz** [comment]
Solved conflicts in new PR #882

**Comment by thomasmerz** [comment]
@cryptogap , thanks for merging. But by merging and closing PR #882 this issue should
a) also got closed (it's still open)
b) don't have any conflicts left 👆🏼 
Can you explain and/or **close this issue** please?

**Comment by thomasmerz** [comment]
@cryptogap , please close this issue as completed by PR #882. Thanks 😘

**Pull request closed without merging**
