### PR TITLE
Automating generation of No IP files

### PR DESCRIPTION
**Pull request by fishcharlie**
This PR adds a script so that whenever a new commit is created (on the master branch), GitHub Actions will automatically generate the no ip files.

This required a few fixes to certain files which you can find in this commit: https://github.com/blocklistproject/Lists/commit/87dc52662eb46ffadb2873cffe46d6c0f9549192.

I have not actually tested the GitHub Actions part of this PR. After this PR gets merged in, I will monitor the status and submit and fixes as/if needed.

If you would like to see the changes this PR will make to the no IP lists you can clone the repo, then run the following in your command line from the root of the project:

`node scripts/generate-noip.js`

Ensure that you are running at least Node.js v15+ or else the command will fail.

If this turns out to be successful, I will work to submit additional PRs for the following tasks:

- dnsmasq automation
- Everything list automation
- `Total number of network filters` header automation

Overtime we could even look into automatically generating pull requests from issues that are created.

Please let me know if there are any issues with this, and hopefully it is the first step towards more automation in this project. 🎉 

#283

### CODE REVIEW

**Comment by blocklistproject** [comment]
THANK YOU VERY MUCH. This will cut down maintenance time by a good bit

**Comment by fishcharlie** [comment]
@blocklistproject Of course!

For reference this is the commit that occurred from this work:

https://github.com/blocklistproject/Lists/commit/73132f04881c141216dfc5a1f953bcd08dad7670

I see some problems with it. Likely due to errors in the original files. Looks like some items are on a single line. And where there is `#0.0.0.0` instead of `# 0.0.0.0` that is also causing problems.

I'll find some time soon to look through that in more detail and fix that up. Then it'll be onto dnsmasq automation.

**Comment by fishcharlie** [comment]
The original GitHub Actions automation went a lot smoother than I expected tho. I expected some type of error or problem that we'd have to fix, but it went really well which is great!

Feel free to review that commit and call out any problems you see.

**Comment by blocklistproject** [comment]
I have tried to modify what you create to create the dnsmasq very. I learn by doing. Hopefully I got it. I am unsure of how to add the "/" at the end of each line.

**Comment by fishcharlie** [comment]
@blocklistproject I see a problem going on. I think we need to have 1 GitHub Actions workflow for both automations. Otherwise it'll conflict with each other and we'll get errors.

Maybe just have 1 file called `run-automations.yml` that looks like this?

```
name: CI
on:
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: node scripts/generate-noip.js
      - run: node scripts/generate-dnsmasq.js
      - name: Commit & Push
        uses: actions-x/commit@v2
        with:
          email: noreply@blocklist.site
          name: GitHub Actions
          branch: master
```

**Comment by fishcharlie** [comment]
@blocklistproject Try changing line 11 from:

```
// .replaceAll(/^# 0\.0\.0\.0 /gmu, "# server=/") // I need this line to add "/" at the end of each URL
```

to:

```
.replaceAll(/^(.*)$/gmu, "$0/") // I need this line to add "/" at the end of each URL
```

**Comment by blocklistproject** [comment]
Changes made. Lets see how that works.

**Comment by fishcharlie** [comment]
@blocklistproject Oh wait that code won't work

**Comment by fishcharlie** [comment]
@blocklistproject There we go. Updated. I think that should work. Might be worth testing it locally first.

**Comment by fishcharlie** [comment]
I use [regex101.com](https://regex101.com) to test that stuff and forgot to set it to JavaScript:

image

**Comment by blocklistproject** [comment]
That is a really nice site. I will have to play with it later. 

I am not on my normal dev computer so I don't have anything installed.

**Comment by fishcharlie** [comment]
@blocklistproject Yeah. That looks really good. Only problem I see is that a lot of the header information now has `/` at the end of each line. Forgot about that edge case.

Sadly I have some other things I need to take care of, but I can try to find time to help look at this later. Making some really great progress!!

Also need to be sure to update the contributing guidelines (notifying users not to update the dnsmasq folder) and README with the new links.

**Comment by blocklistproject** [comment]
@fishcharlie Thank you so much for all your help. This is such a huge help.

**Pull request merged**
