### PR TITLE
Adding `4wsko.r.a.d.sendibm1.com` to phishing list

### PR DESCRIPTION
**Pull request by fishcharlie**
## Summary

Adding `4wsko.r.a.d.sendibm1.com` to phishing list.

I have **not** verified or clicked on this link. However, I received what looks to be a phishing email with a link to a path on this domain.

## Checklist

- [x] I have verified that I have not modified any files inside the `alt-version` folder (automated code will automatically update those files)

- [x] I have verified that I have not modified any files inside the `dnsmasq-version` folder (automated code will automatically update those files)

### CODE REVIEW

**Comment by cryptogap** [comment]
I believe it was closed because the checks were failing

**Comment by fishcharlie** [comment]
@cryptogap I think I resolved everything here. Let me know if there is anything else that needs to be done to get this merged in.

**Comment by spirillen** [comment]
that is redirecting to: `https://www.sendinblue.com/` what/where is the phishing??

**Comment by fishcharlie** [comment]
@spirillen This was a phishing email I received. I tried to search and find it, however I could not find the email.

Part of the problem with @cryptogap closing this 3 days after creation with no explanation is a lot of this important back and forth context gets lost. This PR was created 2 months ago. Hard to remember everything about it during that time.

I do take a lot of responsibility for not adding more detail here. I should have attached screenshots and more proof about what was going on. I didn't expect it to go this long without resolution tho.

Overall a major process failure on many levels. We need a better PR template to get those questions answered, we need faster reviews, and we need explanations as to why something is closed. Maybe there are better ways to streamline this in the future, but those are the things that come to mind.

---

Anyways. I'm confident in this PR. I know this domain was a phishing site when I submitted this PR. It's really just my word you have to rely on tho. So I completely understand if that's not enough to go on and this PR gets closed. Although I think it's far better to have false positives as opposed to false negatives.

And at the very least these process failures need to be cleaned up.

**Comment by spirillen** [comment]
Long answer, with some good points.

And I agree with all of them, hence my issue templates layout + tags should end up ensuring these information's, as nobody can remember WHY they added something a week ago.

You are free to peek into how I have constructed my templates here:
- https://mypdns.org/my-privacy-dns/matrix/-/tree/master/.gitlab/issue_templates
- https://mypdns.org/my-privacy-dns/porn-records/-/tree/master/.gitlab/issue_templates
- https://github.com/mitchellkrogza/phishing/pull/98 (building a new one with the new .yml)

If you come of with some idea for suggestion, please let me know.

**Pull request merged**
